name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 29trxngxx/jenkins-learning:latest .

      - name: Push Docker image to Docker Hub
        run: docker push 29trxngxx/jenkins-learning:latest        

      - name: Trigger Jenkins Job
      if: success()
      run: |
        curl -X POST \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          "${{ secrets.JENKINS_URL }}/job/Jenkins-Learning/build?token=${{ secrets.JENKINS_JOB_TOKEN }}"   